importClass(Packages.com.tivoli.am.fim.trustserver.sts.utilities.IDMappingExtUtils);
importClass(Packages.com.ibm.security.access.httpclient.HttpClient);


IDMappingExtUtils.traceString("\nENTERED PREAUTH_NOTIFY\n" + JSON.stringify(preauth, undefined, 4));
IDMappingExtUtils.traceString("CODE::" + preauth.getTransactionCode());
var headers = new Headers();

headers.addHeader('Content-Type','application/json');
let payload = {
    "message": "Here is your credential authorization code.  Enjoy!",
    "txCode": preauth.getTransactionCode(),   // The tx_code has been generated by the OP,  We just include it in the OOB delivery payload to the user
};

IDMappingExtUtils.traceString("payload: " + JSON.stringify(payload));

// The delivery address really should be something specific to the user
// who is currently initiating a credential offer via the credential issuer.
// The credential issuer is assumed to have asserted the user id by some secure
// mechanism, e.g. signed JWT at /preauth endpoint
let resp = HttpClientV2.httpPost("http://host.docker.internal:8888/txcode", headers, JSON.stringify(payload), null, null, null, null, null, null, null, null, true, null)
