/*
 * IBM Confidential
 * PID 5725-V89 5725-V90 5737-F02
 *
 * Copyright IBM Corp. 2022, 2024
 */

CREATE TABLE OAUTH20_TOKEN_CACHE
(
    TOKEN_ID          VARCHAR(512) NOT NULL
        CONSTRAINT PK_LOOKUPKEY PRIMARY KEY,
    TYPE              VARCHAR(64)  NOT NULL,
    SUB_TYPE          VARCHAR(64),
    DATE_CREATED      BIGINT,
    DATE_LAST_USED    BIGINT,
    LIFETIME          INT,
    TOKEN_STRING      VARCHAR(512) NOT NULL,
    CLIENT_ID         VARCHAR(256) NOT NULL,
    USERNAME          VARCHAR(256) NOT NULL,
    SCOPE             VARCHAR(512) NOT NULL,
    REDIRECT_URI      VARCHAR(256),
    STATE_ID          VARCHAR(64)  NOT NULL,
    TOKEN_ENABLED     CHAR         NOT NULL,
    PREV_TOKEN_STRING VARCHAR(512),
    CHECK (TOKEN_ENABLED IN ('Y', 'N'))
);

CREATE INDEX OAUTH20CACHE_ST ON OAUTH20_TOKEN_CACHE (STATE_ID ASC);
CREATE INDEX OAUTH20CACHE_TKSTRING ON OAUTH20_TOKEN_CACHE (TOKEN_STRING);
CREATE INDEX OAUTH20CACHE_PTKSTRING ON OAUTH20_TOKEN_CACHE (PREV_TOKEN_STRING);
CREATE INDEX OAUTH20CACHE_LIFETIME ON OAUTH20_TOKEN_CACHE (LIFETIME ASC);
CREATE INDEX OAUTH20CACHE_UCID ON OAUTH20_TOKEN_CACHE (USERNAME, CLIENT_ID);


CREATE TABLE OAUTH20_TOKEN_EXTRA_ATTRIBUTE
(
    STATE_ID   VARCHAR(256),
    ATTR_NAME  VARCHAR(256),
    ATTR_VALUE VARCHAR(256),
    SENSITIVE  CHAR DEFAULT 'N',
    READ_ONLY  CHAR DEFAULT 'N',
    CHECK (SENSITIVE IN ('Y', 'N')),
    CHECK (READ_ONLY IN ('Y', 'N'))
);

CREATE INDEX EXTRAATTR_STATE_ID ON OAUTH20_TOKEN_EXTRA_ATTRIBUTE (STATE_ID ASC);
CREATE INDEX EXTRAATTR_NAME ON OAUTH20_TOKEN_EXTRA_ATTRIBUTE (ATTR_NAME ASC);


CREATE TABLE OAUTH20_JTI
(
    JWT_TYPE   INT           NOT NULL,
    JWT_ID     VARCHAR(200)  NOT NULL,
    EXPIRED_AT BIGINT NOT NULL,

    CONSTRAINT PK_JTIS PRIMARY KEY (JWT_TYPE, JWT_ID)
);

CREATE INDEX JTIS_EXPIRED ON OAUTH20_JTI (EXPIRED_AT);

CREATE TABLE OAUTH_TRUSTED_CLIENT
(
    TRUSTED_CLIENT_ID VARCHAR(256) NOT NULL
        CONSTRAINT PK_UNIQUEID PRIMARY KEY,
    USERNAME          VARCHAR(256) NOT NULL,
    CLIENT_ID         VARCHAR(256) NOT NULL
);

CREATE INDEX TRUSTEDCLIENTS_USERNAME ON OAUTH_TRUSTED_CLIENT (USERNAME);
CREATE INDEX TRUSTEDCLIENTS_USERNAMECLIENTID ON OAUTH_TRUSTED_CLIENT (USERNAME, CLIENT_ID);


CREATE TABLE OAUTH_SCOPE
(
    TRUSTED_CLIENT_ID VARCHAR(256) NOT NULL,
    SCOPE             VARCHAR(256) NOT NULL,

    CONSTRAINT PK_UNIQUEIDSCOPE PRIMARY KEY (TRUSTED_CLIENT_ID, SCOPE),
    FOREIGN KEY (TRUSTED_CLIENT_ID) REFERENCES OAUTH_TRUSTED_CLIENT (TRUSTED_CLIENT_ID) ON DELETE CASCADE
);



CREATE TABLE OAUTH20_DYNAMIC_CLIENT
(
    CLIENT_ID       VARCHAR(256) NOT NULL
        CONSTRAINT DYN_PK_LOOKUPKEY PRIMARY KEY,
    DEFINITION_ID   BIGINT       NOT NULL,
    DEFINITION_NAME VARCHAR(200),
    OWNER_USERNAME  VARCHAR(256),
    DYN_DATA        CLOB
);

CREATE INDEX OAUTH20DYNCLIENT_DEF ON OAUTH20_DYNAMIC_CLIENT (DEFINITION_ID);
CREATE INDEX OAUTH20DYNCLIENTS_USER ON OAUTH20_DYNAMIC_CLIENT (OWNER_USERNAME);


CREATE TABLE DMAP_ENTRIES
(
    DMAP_KEY       VARCHAR(256) NOT NULL,
    DMAP_PARTITION VARCHAR(256) NOT NULL,
    DMAP_VALUE     CLOB         NOT NULL,
    DMAP_EXPIRY    BIGINT,
    PRIMARY KEY (DMAP_KEY, DMAP_PARTITION)
);

CREATE INDEX DMAP_EXPIRY_INDEX ON DMAP_ENTRIES (DMAP_EXPIRY);

ALTER TABLE OAUTH20_TOKEN_EXTRA_ATTRIBUTE ALTER COLUMN ATTR_VALUE SET DATA TYPE VARCHAR(1024);

COMMIT;
